Respect the remote_tmp setting
ansible-collections/cloud.common pull request #63
Opened 2021-06-22 10:25 UTC by NeonSludge

##### SUMMARY
This PR makes the turbo module respect custom remote Ansible temporary directories set by the `remote_tmp` setting in `ansible.cfg` or by the `ANSIBLE_REMOTE_TMP` environment variable.
This is necessary because in its current state the module will always try to create a socket in the default `$HOME/.ansible/tmp` temporary directory which may be missing if a custom `remote_tmp` is set.

##### ISSUE TYPE
- Bugfix Pull Request

2021-06-23 18:40 UTC, goneri commented
Hi @NeonSludge, thank you for the PR.

By default `remote_tmp` comes with `~/.ansible/tmp`. We need to `expanduser()` the string to get an usuable absolute path.

Can you apply this change, or something similar. Also, we need a changelog fragment with the PR: https://docs.ansible.com/ansible/latest/community/development_process.html#creating-a-changelog-fragment

```path
diff --git a/plugins/module_utils/turbo/module.py b/plugins/module_utils/turbo/module.py
index 938ce76..156b775 100644
--- a/plugins/module_utils/turbo/module.py
+++ b/plugins/module_utils/turbo/module.py
@@ -3,7 +3,6 @@ import os
 import socket
 import sys
 import time
-
 import ansible.module_utils.basic
 from .exceptions import (
     EmbeddedModuleSuccess,
@@ -88,8 +87,10 @@ class AnsibleTurboModule(ansible.module_utils.basic.AnsibleModule):
             self.run_on_daemon()
 
     def socket_path(self):
+        from os.path import expanduser
+        abs_remote_tmp = expanduser(self._remote_tmp)
         return (
-            self._remote_tmp
+            abs_remote_tmp
             + f"/turbo_mode.{self.collection_name}.socket"
         )
```

2021-07-28 12:43 UTC, abikouo commented on tests/integration/targets/turbo_mode/tasks/main.yaml
> +      - _result.counter == 1
```suggestion
- assert:
    that:
      - _result.counter == 1

- name: test using default remote_tmp. socket previously created
  cloud.common.turbo_demo:
  register: _result

- assert:
        that:
        - _result.counter > 1
```

2021-07-28 12:44 UTC, abikouo requested changes

2021-07-28 12:44 UTC, abikouo commented on tests/integration/targets/turbo_mode/tasks/main.yaml
> +      - _result.counter == 1
this test aims to validate that the new socket creation is not due to an expired TTL for the previous socket

2021-07-29 10:09 UTC, abikouo approved these changes

2021-07-29 11:35 UTC, merged